import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Playfair } from "next/font/google";
import { Playwrite_CU_Guides } from "next/font/google";
import { Comic_Neue } from "next/font/google";
import Preloader from "@/components/Preloader";


export const metadata: Metadata = {
	title: "Harshit Sharma - Student | Full Stack Developer",
	description: "Generated by create next app",
};

const geistSans = Geist({
	variable: "--font-geist-sans",
	subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-geist-mono",
	subsets: ["latin"],
});

const comicNeue = Comic_Neue({
	variable: "--font-comic-neue",
	subsets: ["latin"],
	weight: ["400", "300", "700"],
});



export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className="no-scrollbar">
			<head>
				<meta name="google-site-verification" content="x6fanuK-vqvY8EefCAQN0DNrNLg69JlbEEZGkXxiuVI" />
			</head>
			<body
				className={`no-scrollbar ${geistSans.variable} ${geistMono.variable} ${comicNeue.variable} antialiased dark`}
			>
				<Preloader />
				{children}
			</body>
		</html>
	);
}
